version: '3.9'
  
volumes:
  nginx-shared:

services:

  # Safe Transaction Service


  # Safe Config Service
  nginx:
    image: nginx:1.20-alpine
    env_file:
      - container_env_files/cfg.env
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT_CFG}
    depends_on:
      - cfg-web
  
  db:
    image: postgres:13-alpine
    env_file:
      - container_env_files/cfg.env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  cfg-web:
    image: gnosispm/safe-config-service:${CFG_VERSION}
    tty: true
    volumes:
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT_CFG}
    env_file:
      - container_env_files/cfg.env
    depends_on:
      - db
  
  # Safe Client Gateway
  redis:
    image: redis:5-alpine

  cgw:
    image: gnosispm/safe-client-gateway:${CGW_VERSION}
    env_file:
      - container_env_files/cgw.env
    depends_on:
      - redis
    ports:
      - ${CGW_PORT}:3666
