version: '3.9'
  
volumes:
  nginx-shared-txs:
  nginx-shared-cfg:

services:

  # Safe Transaction Service
  nginx-txs:
    image: nginx:alpine
    ports:
      - "${REVERSE_PROXY_PORT}:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared-txs:/nginx
    depends_on:
      - txs-web, cfg-web, cgw-web

  redis-txs:
    image: redis:alpine

  db-txs:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  txs-web:
    image: gnosispm/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    environment:
      - ETHEREUM_NODE_URL=${RPC_NODE_URL}
    depends_on:
      - db-txs
      - redis-txs
    working_dir: /app
    volumes:
      - nginx-shared-txs:/nginx
    command: docker/web/run_web.sh

  worker: &worker
    image: gnosispm/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    environment:
      - ETHEREUM_NODE_URL=${RPC_NODE_URL}
    depends_on:
      - db-txs
      - redis-txs
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh  

  # Safe Config Service
  db:
    image: postgres:13-alpine
    env_file:
      - container_env_files/cfg.env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  cfg-web:
    image: gnosispm/safe-config-service:${CFG_VERSION}
    tty: true
    volumes:
      - nginx-shared-cfg:/nginx
    env_file:
      - container_env_files/cfg.env
    depends_on:
      - db
  
  # Safe Client Gateway
  redis:
    image: redis:5-alpine

  cgw-web:
    image: gnosispm/safe-client-gateway:${CGW_VERSION}
    env_file:
      - container_env_files/cgw.env
    depends_on:
      - redis
    ports: 
      - "3666"
